FROM node:20-alpine AS build

ARG VITE_API_KEY=""
WORKDIR /app
ENV NODE_ENV=production
ENV VITE_API_KEY=$VITE_API_KEY
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY deploy/nginx/frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
