"""Pydantic models for Polymarket API responses."""

import json
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field, field_validator


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class GammaMarket(BaseModel):
    """Market from Gamma API."""

    id: str = ""
    condition_id: str = Field(default="", alias="conditionId")
    question: str = ""
    slug: str = ""
    end_date_iso: str = Field(default="", alias="endDateIso")
    game_start_time: str | None = Field(default=None, alias="gameStartTime")
    description: str = ""
    outcomes: list[str] = Field(default_factory=list)
    outcome_prices: str = Field(default="", alias="outcomePrices")

    @field_validator("outcomes", mode="before")
    @classmethod
    def _parse_outcomes(cls, v):
        """Gamma API returns outcomes as a JSON string, e.g. '[\"Yes\",\"No\"]'."""
        if isinstance(v, str):
            try:
                return json.loads(v)
            except (json.JSONDecodeError, TypeError):
                return []
        return v
    volume: float = 0.0
    liquidity: float = 0.0
    active: bool = True
    closed: bool = False
    archived: bool = False
    category: str = Field(default="", alias="groupItemTitle")
    clob_token_ids: str = Field(default="", alias="clobTokenIds")
    accepting_orders: bool = Field(default=True, alias="acceptingOrders")

    model_config = {"populate_by_name": True}

    @property
    def end_date(self) -> datetime | None:
        if not self.end_date_iso:
            return None
        try:
            return datetime.fromisoformat(self.end_date_iso.replace("Z", "+00:00"))
        except (ValueError, AttributeError):
            return None

    @property
    def outcome_price_list(self) -> list[float]:
        if not self.outcome_prices:
            return []
        try:
            parsed = json.loads(self.outcome_prices)
            return [float(p) for p in parsed]
        except (json.JSONDecodeError, ValueError, TypeError):
            return []

    @property
    def token_ids(self) -> list[str]:
        if not self.clob_token_ids:
            return []
        try:
            parsed = json.loads(self.clob_token_ids)
            return [str(t) for t in parsed]
        except (json.JSONDecodeError, ValueError, TypeError):
            return []

    @property
    def yes_price(self) -> float | None:
        prices = self.outcome_price_list
        return prices[0] if prices else None

    @property
    def no_price(self) -> float | None:
        prices = self.outcome_price_list
        return prices[1] if len(prices) > 1 else None


class OrderBookEntry(BaseModel):
    price: float
    size: float


class OrderBook(BaseModel):
    market: str = ""
    asset_id: str = ""
    bids: list[OrderBookEntry] = Field(default_factory=list)
    asks: list[OrderBookEntry] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    @property
    def best_bid(self) -> float | None:
        return self.bids[0].price if self.bids else None

    @property
    def best_ask(self) -> float | None:
        return self.asks[0].price if self.asks else None

    @property
    def spread(self) -> float | None:
        if self.best_bid is not None and self.best_ask is not None:
            return self.best_ask - self.best_bid
        return None

    @property
    def mid_price(self) -> float | None:
        if self.best_bid is not None and self.best_ask is not None:
            return (self.best_bid + self.best_ask) / 2
        return None


class TradeSignal(BaseModel):
    """Signal generated by a strategy."""

    strategy: str
    market_id: str
    token_id: str
    question: str = ""
    side: OrderSide
    outcome: str = ""
    estimated_prob: float
    market_price: float
    edge: float
    size_usd: float
    confidence: float
    reasoning: str = ""
    metadata: dict = Field(default_factory=dict)


class PositionInfo(BaseModel):
    """Current position from Data API."""

    market_id: str = ""
    token_id: str = ""
    outcome: str = ""
    size: float = 0.0
    avg_price: float = 0.0
    current_price: float = 0.0
    unrealized_pnl: float = 0.0

    @property
    def market_value(self) -> float:
        return self.size * self.current_price

    @property
    def cost_basis(self) -> float:
        return self.size * self.avg_price
